

const sortOrderData =  {
    "extends": "stylelint-config-recommended",
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
        "no-descending-specificity": null,
        "indentation": "tab",
        "order/order": [
            "dollar-variables",
            "at-variables",
            "custom-properties",
            "declarations",
            "at-rules",
            "rules"
        ],
        "order/properties-order": [
            {
                "properties": [
                    "all",
                    "content"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "position",
                    "z-index",
                    "top",
                    "right",
                    "bottom",
                    "left"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "display",
                    "visibility",
                    "float",
                    "clear",
                    "overflow",
                    "overflow-x",
                    "overflow-y",
                    "clip",
                    "zoom",
                    "order",
                    "align-content",
                    "align-items",
                    "align-self",
                    "flex",
                    "flex-basis",
                    "flex-direction",
                    "flex-flow",
                    "flex-grow",
                    "flex-shrink",
                    "flex-wrap",
                    "justify-content",
                    "grid",
                    "grid-auto-columns",
                    "grid-auto-flow",
                    "grid-column-end",
                    "grid-column-gap",
                    "grid-column-start",
                    "grid-column",
                    "grid-gap",
                    "grid-row-end",
                    "grid-row-gap",
                    "grid-row-start",
                    "grid-row",
                    "grid-template-areas",
                    "grid-template-columns",
                    "grid-template-rows",
                    "grid-template",
                    "grid"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "box-sizing",
                    "width",
                    "min-width",
                    "max-width",
                    "height",
                    "min-height",
                    "max-height",
                    "padding",
                    "padding-top",
                    "padding-right",
                    "padding-bottom",
                    "padding-left",
                    "margin",
                    "margin-top",
                    "margin-right",
                    "margin-bottom",
                    "margin-left"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "font",
                    "font-family",
                    "font-size",
                    "font-weight",
                    "font-style",
                    "font-variant",
                    "font-size-adjust",
                    "font-stretch",
                    "font-effect",
                    "font-emphasize",
                    "font-emphasize-position",
                    "font-emphasize-style",
                    "font-smooth",
                    "line-height",
                    "color",
                    "quotes",
                    "text-align",
                    "text-align-last",
                    "text-shadow",
                    "vertical-align",
                    "white-space",
                    "text-decoration",
                    "text-emphasis",
                    "text-emphasis-color",
                    "text-emphasis-style",
                    "text-emphasis-position",
                    "text-indent",
                    "text-justify",
                    "text-transform",
                    "letter-spacing",
                    "word-spacing",
                    "text-outline",
                    "text-transform",
                    "text-wrap",
                    "text-overflow",
                    "text-overflow-ellipsis",
                    "text-overflow-mode",
                    "word-wrap",
                    "word-break",
                    "tab-size",
                    "hyphens",
                    "counter-reset",
                    "counter-increment"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "table-layout",
                    "empty-cells",
                    "caption-side",
                    "border-spacing",
                    "border-collapse",
                    "list-style",
                    "list-style-type",
                    "list-style-position",
                    "list-style-image",
                    "resize",
                    "cursor",
                    "user-select",
                    "pointer-events"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "background",
                    "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader",
                    "background-color",
                    "background-image",
                    "background-repeat",
                    "background-attachment",
                    "background-position",
                    "background-position-x",
                    "background-position-y",
                    "background-clip",
                    "background-origin",
                    "background-size",
                    "background-blend-mode",
                    "border",
                    "border-collapse",
                    "border-width",
                    "border-style",
                    "border-color",
                    "border-top",
                    "border-top-width",
                    "border-top-style",
                    "border-top-color",
                    "border-right",
                    "border-right-width",
                    "border-right-style",
                    "border-right-color",
                    "border-bottom",
                    "border-bottom-width",
                    "border-bottom-style",
                    "border-bottom-color",
                    "border-left",
                    "border-left-width",
                    "border-left-style",
                    "border-left-color",
                    "border-radius",
                    "border-top-left-radius",
                    "border-top-right-radius",
                    "border-bottom-right-radius",
                    "border-bottom-left-radius",
                    "border-image",
                    "border-image-source",
                    "border-image-slice",
                    "border-image-width",
                    "border-image-outset",
                    "border-image-repeat",
                    "outline",
                    "outline-width",
                    "outline-style",
                    "outline-color",
                    "outline-offset",
                    "box-decoration-break",
                    "opacity",
                    "box-shadow"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "transition",
                    "transition-delay",
                    "transition-timing-function",
                    "transition-duration",
                    "transition-property",
                    "transform",
                    "transform-origin",
                    "animation",
                    "animation-name",
                    "animation-duration",
                    "animation-play-state",
                    "animation-timing-function",
                    "animation-delay",
                    "animation-iteration-count",
                    "animation-iteration-count",
                    "animation-direction"
                ]
            }
        ]
    }
}
module.exports = sortOrderData;